const sports = [
  {
    id: 1,
    name: "Running",
    description: "High-intensity cardio activity that burns a lot of calories.",
    image: "http://localhost:5000/images/sports/running.jpg",
    caloriesPer30Min: 300,
  },
  {
    id: 2,
    name: "Cycling",
    description: "A great low-impact cardio workout for building endurance.",
    image: "http://localhost:5000/images/sports/cycling.webp",
    caloriesPer30Min: 250,
  },
  {
    id: 3,
    name: "Swimming",
    description: "A full-body workout that strengthens muscles and burns calories.",
    image: "http://localhost:5000/images/sports/swimming.webp",
    caloriesPer30Min: 350,
  },
  {
    id: 4,
    name: "Yoga",
    description: "Promotes flexibility, strength, and relaxation.",
    image: "http://localhost:5000/images/sports/yoga.jpeg",
    caloriesPer30Min: 150,
  },
  {
    id: 5,
    name: "Weightlifting",
    description: "Builds muscle and boosts metabolism.",
    image: "http://localhost:5000/images/sports/weightlifting.jpg",
    caloriesPer30Min: 200,
  },
  {
    id: 6,
    name: "Basketball",
    description: "Fast-paced team sport that burns calories and improves coordination.",
    image: "http://localhost:5000/images/sports/basketball.jpg",
    caloriesPer30Min: 300,
  },
  {
    id: 7,
    name: "Tennis",
    description: "Intense sport that improves agility and burns calories.",
    image: "http://localhost:5000/images/sports/tennis.jpg",
    caloriesPer30Min: 280,
  },
  {
    id: 8,
    name: "Soccer",
    description: "High-intensity team sport that involves constant running.",
    image: "http://localhost:5000/images/sports/soccer.jpg",
    caloriesPer30Min: 300,
  },
  {
    id: 9,
    name: "Rowing",
    description: "Full-body workout that strengthens muscles and boosts endurance.",
    image: "http://localhost:5000/images/sports/rowing.jpg",
    caloriesPer30Min: 260,
  },
  {
    id: 10,
    name: "Hiking",
    description: "Outdoor activity that burns calories while enjoying nature.",
    image: "http://localhost:5000/images/sports/hiking.jpg",
    caloriesPer30Min: 220,
  },
  {
    id: 11,
    name: "Boxing",
    description: "High-intensity sport that builds endurance and burns calories.",
    image: "http://localhost:5000/images/sports/boxing.jpeg",
    caloriesPer30Min: 400,
  },
  {
    id: 12,
    name: "Martial Arts",
    description: "Combines strength, agility, and endurance training.",
    image: "http://localhost:5000/images/sports/martial-arts.jpg",
    caloriesPer30Min: 350,
  },
  {
    id: 13,
    name: "Skating",
    description: "Improves balance, coordination, and burns calories.",
    image: "http://localhost:5000/images/sports/skating.jpeg",
    caloriesPer30Min: 250,
  },
  {
    id: 14,
    name: "Skiing",
    description: "Full-body winter sport that burns calories and builds endurance.",
    image: "http://localhost:5000/images/sports/skiing.jpg",
    caloriesPer30Min: 300,
  },
  {
    id: 15,
    name: "Golf (Walking)",
    description: "Low-intensity sport that improves focus and burns calories.",
    image: "http://localhost:5000/images/sports/golf.jpg",
    caloriesPer30Min: 120,
  },
  {
    id: 16,
    name: "Cricket",
    description: "Team sport that improves coordination and burns calories.",
    image: "http://localhost:5000/images/sports/cricket.jpg",
    caloriesPer30Min: 200,
  },
  {
    id: 17,
    name: "Badminton",
    description: "Fast-paced racket sport that burns calories and improves reflexes.",
    image: "http://localhost:5000/images/sports/badminton.jpg",
    caloriesPer30Min: 270,
  },
  {
    id: 18,
    name: "Volleyball",
    description: "Team sport that improves agility and coordination.",
    image: "http://localhost:5000/images/sports/volleyball.jpg",
    caloriesPer30Min: 200,
  },
  {
    id: 19,
    name: "Surfing",
    description: "Water sport that improves balance and burns calories.",
    image: "http://localhost:5000/images/sports/surfing.avif",
    caloriesPer30Min: 230,
  },
  {
    id: 20,
    name: "Jump Rope",
    description: "High-intensity workout for cardio and endurance.",
    image: "http://localhost:5000/images/sports/jump-rope.jpg",
    caloriesPer30Min: 400,
  },
  {
    id: 21,
    name: "Rock Climbing",
    description: "Strengthens muscles and improves endurance.",
    image: "http://localhost:5000/images/sports/rock-climbing.jpg",
    caloriesPer30Min: 320,
  },
  {
    id: 22,
    name: "Zumba",
    description: "Dance-based cardio workout that burns calories and boosts energy.",
    image: "http://localhost:5000/images/sports/zumba.jpg",
    caloriesPer30Min: 300,
  },
  {
    id: 23,
    name: "CrossFit",
    description: "High-intensity functional training program.",
    image: "http://localhost:5000/images/sports/crossfit.jpg",
    caloriesPer30Min: 400,
  },
  {
    id: 24,
    name: "Elliptical Trainer",
    description: "Low-impact cardio workout that burns calories effectively.",
    image: "http://localhost:5000/images/sports/elliptical.webp",
    caloriesPer30Min: 270,
  },
  {
    id: 25,
    name: "Table Tennis",
    description: "Fast-paced indoor sport that improves hand-eye coordination.",
    image: "http://localhost:5000/images/sports/table-tennis.jpg",
    caloriesPer30Min: 180,
  },
  {
    id: 26,
    name: "Kayaking",
    description: "Water sport that strengthens upper body and core muscles.",
    image: "http://localhost:5000/images/sports/kayaking.webp",
    caloriesPer30Min: 250,
  },
  {
    id: 27,
    name: "Horseback Riding",
    description: "Equestrian activity that improves balance and burns calories.",
    image: "http://localhost:5000/images/sports/horseback-riding.jpg",
    caloriesPer30Min: 200,
  },
  {
    id: 28,
    name: "Pilates",
    description: "Low-impact workout that improves flexibility and strengthens core muscles.",
    image: "http://localhost:5000/images/sports/pilates.jpg",
    caloriesPer30Min: 150,
  },
  {
    id: 29,
    name: "Bowling",
    description: "Recreational indoor sport that improves focus and burns calories.",
    image: "http://localhost:5000/images/sports/bowling.jpg",
    caloriesPer30Min: 120,
  },
  {
    id: 30,
    name: "Snowboarding",
    description: "Winter sport that combines balance and cardio activity.",
    image: "http://localhost:5000/images/sports/snowboarding.jpg",
    caloriesPer30Min: 300,
  },
  {
    id: 31,
    name: "Ice Hockey",
    description: "Fast-paced team sport on ice that burns calories and improves coordination.",
    image: "http://localhost:5000/images/sports/ice-hockey.jpg",
    caloriesPer30Min: 400,
  },
  {
    id: 32,
    name: "Archery",
    description: "Precision-based sport that improves focus and burns calories.",
    image: "http://localhost:5000/images/sports/archery.jpg",
    caloriesPer30Min: 140,
  },
  {
    id: 33,
    name: "Rollerblading",
    description: "Outdoor activity that strengthens lower body and improves cardio.",
    image: "http://localhost:5000/images/sports/rollerblading.webp",
    caloriesPer30Min: 300,
  },
];

module.exports = sports;
