const supplements = [
    {
        id: 1,
        name: "Whey Protein",
        category: "Protein Supplement",
        description: "Helps in muscle building and recovery.",
        brand: "Optimum Nutrition",
        image: "http://localhost:5000/images/protein/whey-optimum.jpg",
    },
    {
        id: 2,
        name: "Casein Protein",
        category: "Protein Supplement",
        description: "Slow-digesting protein ideal for nighttime recovery.",
        brand: "MuscleTech",
        image: "http://localhost:5000/images/protein/casein-protein.webp",
    },
    {
        id: 3,
        name: "Soy Protein Isolate",
        category: "Protein Supplement",
        description: "Plant-based protein for muscle repair and growth.",
        brand: "NOW Sports",
        image: "http://localhost:5000/images/protein/soy-protein.jpeg",
    },
    {
        id: 4,
        name: "Egg White Protein",
        category: "Protein Supplement",
        description: "Low-fat, high-quality protein source.",
        brand: "Jay Robb",
        image: "http://localhost:5000/images/protein/egg-white-protein.webp",
    },
    {
        id: 5,
        name: "Plant-Based Protein",
        category: "Protein Supplement",
        description: "A blend of plant proteins for vegans.",
        brand: "Garden of Life",
        image: "http://localhost:5000/images/protein/plant-protein.avif",
    },
    {
        id: 6,
        name: "Pea Protein",
        category: "Protein Supplement",
        description: "Rich in amino acids and iron.",
        brand: "Orgain",
        image: "http://localhost:5000/images/protein/pea-protein.webp",
    },
    {
        id: 7,
        name: "Rice Protein",
        category: "Protein Supplement",
        description: "Hypoallergenic protein for sensitive individuals.",
        brand: "NutriBiotic",
        image: "http://localhost:5000/images/protein/rice-protein.webp",
    },
    {
        id: 8,
        name: "Collagen Protein",
        category: "Protein Supplement",
        description: "Supports joint and skin health.",
        brand: "Vital Proteins",
        image: "http://localhost:5000/images/protein/collagen-protein.webp",
    },
    {
        id: 9,
        name: "Hemp Protein",
        category: "Protein Supplement",
        description: "High in omega-3 and omega-6 fatty acids.",
        brand: "Nutiva",
        image: "http://localhost:5000/images/protein/hemp-protein.webp",
    },
    {
        id: 10,
        name: "Protein Blend",
        category: "Protein Supplement",
        description: "Combines multiple protein sources for maximum benefit.",
        brand: "BSN Syntha-6",
        image: "http://localhost:5000/images/protein/protein-blend.jpg",
    },
    {
        id: 11,
        name: "Creatine Monohydrate",
        category: "Performance Supplement",
        description: "Enhances strength, power, and performance.",
        brand: "Optimum Nutrition",
        image: "http://localhost:5000/images/performance/creatine-monohydrate.jpg",
    },
    {
        id: 12,
        name: "Beta-Alanine",
        category: "Performance Supplement",
        description: "Reduces fatigue and increases endurance.",
        brand: "Cellucor",
        image: "http://localhost:5000/images/performance/beta-alanine.avif",
    },
    {
        id: 13,
        name: "Caffeine Pills",
        category: "Performance Supplement",
        description: "Boosts energy and focus for workouts.",
        brand: "ProLab",
        image: "http://localhost:5000/images/performance/caffeine-pills.jpeg",
    },
    {
        id: 14,
        name: "Pre-Workout Formula",
        category: "Performance Supplement",
        description: "Improves energy and performance during training.",
        brand: "Cellucor",
        image: "http://localhost:5000/images/performance/pre-workout.jpg",
    },
    {
        id: 15,
        name: "BCAA (Branched-Chain Amino Acids)",
        category: "Performance Supplement",
        description: "Supports muscle recovery and reduces soreness.",
        brand: "Scivation Xtend",
        image: "http://localhost:5000/images/performance/bcaa.jpg",
    },
    {
        id: 16,
        name: "Nitric Oxide Booster",
        category: "Performance Supplement",
        description: "Enhances blood flow and muscle pumps.",
        brand: "BSN N.O.-XPLODE",
        image: "http://localhost:5000/images/performance/nitric-oxide.jpg",
    },
    {
        id: 17,
        name: "Electrolyte Powder",
        category: "Performance Supplement",
        description: "Replenishes electrolytes and hydration during workouts.",
        brand: "Ultima Replenisher",
        image: "http://localhost:5000/images/performance/electrolyte-powder.jpg",
    },
    {
        id: 18,
        name: "L-Carnitine",
        category: "Performance Supplement",
        description: "Supports fat metabolism and energy production.",
        brand: "NOW Sports",
        image: "http://localhost:5000/images/performance/l-carnitine.jpg",
    },
    {
        id: 19,
        name: "HMB (Beta-Hydroxy Beta-Methylbutyrate)",
        category: "Performance Supplement",
        description: "Reduces muscle breakdown and improves strength.",
        brand: "Optimum Nutrition",
        image: "http://localhost:5000/images/performance/hmb.jpg",
    },
    {
        id: 20,
        name: "Glutamine Powder",
        category: "Performance Supplement",
        description: "Supports muscle recovery and immune function.",
        brand: "MusclePharm",
        image: "http://localhost:5000/images/performance/glutamine-powder.webp",
    },
    {
        id: 21,
        name: "Multivitamin for Men",
        category: "Vitamin Supplement",
        description: "Comprehensive vitamins and minerals tailored for men’s health.",
        brand: "Optimum Nutrition",
        image: "http://localhost:5000/images/vitamin/multivitamin-men.jpeg",
    },
    {
        id: 22,
        name: "Multivitamin for Women",
        category: "Vitamin Supplement",
        description: "Supports overall health and energy tailored for women.",
        brand: "Optimum Nutrition",
        image: "http://localhost:5000/images/vitamin/multivitamin-women.jpg",
    },
    {
        id: 23,
        name: "Vitamin C with Bioflavonoids",
        category: "Vitamin Supplement",
        description: "Boosts immune function and skin health.",
        brand: "Nature’s Bounty",
        image: "http://localhost:5000/images/vitamin/vitamin-c.webp",
    },
    {
        id: 24,
        name: "Vitamin D3",
        category: "Vitamin Supplement",
        description: "Supports bone health and immune system.",
        brand: "NOW Foods",
        image: "http://localhost:5000/images/vitamin/vitamin-d3.png",
    },
    {
        id: 25,
        name: "Vitamin B12",
        category: "Vitamin Supplement",
        description: "Promotes energy production and supports nervous system health.",
        brand: "Solgar",
        image: "http://localhost:5000/images/vitamin/vitamin-b12.jpg",
    },
    {
        id: 26,
        name: "Fish Oil Omega-3",
        category: "Vitamin Supplement",
        description: "Supports heart, brain, and joint health.",
        brand: "Nordic Naturals",
        image: "http://localhost:5000/images/vitamin/fish-oil.webp",
    },
    {
        id: 27,
        name: "Calcium + Magnesium with Zinc",
        category: "Vitamin Supplement",
        description: "Promotes strong bones and overall health.",
        brand: "Kirkland Signature",
        image: "http://localhost:5000/images/vitamin/calcium-magnesium.jpg",
    },
    {
        id: 28,
        name: "Vitamin E",
        category: "Vitamin Supplement",
        description: "Provides antioxidant support and skin health benefits.",
        brand: "Nature Made",
        image: "http://localhost:5000/images/vitamin/vitamin-e.jpeg",
    },
    {
        id: 29,
        name: "Vitamin K2",
        category: "Vitamin Supplement",
        description: "Supports bone and cardiovascular health.",
        brand: "Sports Research",
        image: "http://localhost:5000/images/vitamin/vitamin-k2.jpg",
    },
    {
        id: 30,
        name: "Biotin (Vitamin B7)",
        category: "Vitamin Supplement",
        description: "Supports healthy hair, skin, and nails.",
        brand: "Natrol",
        image: "http://localhost:5000/images/vitamin/biotin.avif",
    },
    {
        id: 31,
        name: "Hydroxycut Hardcore",
        category: "Weight Loss Supplement",
        description: "Boosts metabolism and energy for weight loss.",
        brand: "MuscleTech",
        image: "http://localhost:5000/images/weightloss/hydroxycut-hardcore.png",
    },
    {
        id: 32,
        name: "Green Tea Extract",
        category: "Weight Loss Supplement",
        description: "Rich in antioxidants, supports fat burning.",
        brand: "NOW Foods",
        image: "http://localhost:5000/images/weightloss/green-tea-extract.webp",
    },
    {
        id: 33,
        name: "CLK Fat-burner",
        category: "Weight Loss Supplement",
        description: "Helps convert fat into energy during workouts.",
        brand: "Cellucor",
        image: "http://localhost:5000/images/weightloss/fatBurner.jpg",
    },
    {
        id: 34,
        name: "CLA (Conjugated Linoleic Acid)",
        category: "Weight Loss Supplement",
        description: "Promotes fat loss and lean muscle retention.",
        brand: "MusclePharm",
        image: "http://localhost:5000/images/weightloss/cla.jpg",
    },
    {
        id: 35,
        name: "Garcinia Cambogia",
        category: "Weight Loss Supplement",
        description: "Reduces appetite and blocks fat production.",
        brand: "NatureWise",
        image: "http://localhost:5000/images/weightloss/garcinia-cambogia.jpg",
    },
    {
        id: 36,
        name: "Raspberry Ketones",
        category: "Weight Loss Supplement",
        description: "Supports fat metabolism and appetite suppression.",
        brand: "Nutricost",
        image: "http://localhost:5000/images/weightloss/raspberry-ketones.webp",
    },
    {
        id: 37,
        name: "Apple Cider Vinegar Gummies",
        category: "Weight Loss Supplement",
        description: "Aids digestion and promotes fat burning.",
        brand: "Goli Nutrition",
        image: "http://localhost:5000/images/weightloss/apple-cider-vinegar.jpg",
    },
    {
        id: 38,
        name: "Fat Burner XT",
        category: "Weight Loss Supplement",
        description: "Combines thermogenics for increased fat burning.",
        brand: "Jacked Factory",
        image: "http://localhost:5000/images/weightloss/fat-burner-xt.jpg",
    },
    {
        id: 39,
        name: "Forskolin",
        category: "Weight Loss Supplement",
        description: "Helps in breaking down stored fat.",
        brand: "NutraHerbals",
        image: "http://localhost:5000/images/weightloss/forskolin.jpg",
    },
    {
        id: 40,
        name: "LeanMode",
        category: "Weight Loss Supplement",
        description: "Supports appetite suppression and weight management.",
        brand: "Evlution Nutrition",
        image: "http://localhost:5000/images/weightloss/leanmode.webp",
    },
    {
        id: 41,
        name: "Serious Mass",
        category: "Mass Gainer",
        description: "High-calorie mass gainer with protein and carbs.",
        brand: "Optimum Nutrition",
        image: "http://localhost:5000/images/massgainer/serious-mass.jpg",
    },
    {
        id: 42,
        name: "Mass-Tech Extreme 2000",
        category: "Mass Gainer",
        description: "Designed for extreme weight gain and muscle building.",
        brand: "MuscleTech",
        image: "http://localhost:5000/images/massgainer/mass-tech.jpg",
    },
    {
        id: 43,
        name: "True-Mass",
        category: "Mass Gainer",
        description: "Premium protein and carb matrix for mass gain.",
        brand: "BSN",
        image: "http://localhost:5000/images/massgainer/true-mass.webp",
    },
    {
        id: 44,
        name: "Pro Gainer",
        category: "Mass Gainer",
        description: "High-protein weight gainer with added vitamins and minerals.",
        brand: "Optimum Nutrition",
        image: "http://localhost:5000/images/massgainer/pro-gainer.webp",
    },
    {
        id: 45,
        name: "Super Mass Gainer",
        category: "Mass Gainer",
        description: "High-calorie formula for size and strength.",
        brand: "Dymatize",
        image: "http://localhost:5000/images/massgainer/super-mass-gainer.webp",
    },
    {
        id: 46,
        name: "Mutant Mass",
        category: "Mass Gainer",
        description: "Designed for hardcore mass gainers.",
        brand: "Mutant",
        image: "http://localhost:5000/images/massgainer/mutant-mass.jpg",
    },
    {
        id: 47,
        name: "Mass Gainer XL",
        category: "Mass Gainer",
        description: "Balanced formula for muscle and mass gain.",
        brand: "Bodybuilding.com Signature",
        image: "http://localhost:5000/images/massgainer/mass-gainer-xl.jpg",
    },
    {
        id: 48,
        name: "Naked Mass",
        category: "Mass Gainer",
        description: "Clean ingredients for healthy mass gain.",
        brand: "Naked Nutrition",
        image: "http://localhost:5000/images/massgainer/naked-mass.webp",
    },
    {
        id: 49,
        name: "Up Your Mass",
        category: "Mass Gainer",
        description: "Muscle mass and recovery support formula.",
        brand: "MHP",
        image: "http://localhost:5000/images/massgainer/up-your-mass.webp",
    },
    {
        id: 50,
        name: "Critical Mass",
        category: "Mass Gainer",
        description: "Helps build muscle and support recovery.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/massgainer/critical-mass.jpg",
    },
    {
        id: 51,
        name: "TestoFuel",
        category: "Testosterone Booster",
        description: "Natural testosterone booster designed to enhance muscle growth and recovery.",
        brand: "Roar Ambition",
        image: "http://localhost:5000/images/testboosters/testofuel.jpg",
    },
    {
        id: 52,
        name: "Prime Male",
        category: "Testosterone Booster",
        description: "Formulated for men over 30 to boost energy, libido, and vitality.",
        brand: "Prime Male",
        image: "http://localhost:5000/images/testboosters/prime-male.webp",
    },
    {
        id: 53,
        name: "Testogen",
        category: "Testosterone Booster",
        description: "Increases natural testosterone production for improved performance.",
        brand: "Testogen",
        image: "http://localhost:5000/images/testboosters/testogen.jpeg",
    },
    {
        id: 54,
        name: "Hunter Test",
        category: "Testosterone Booster",
        description: "Premium testosterone booster for strength and focus.",
        brand: "Hunter Evolve",
        image: "http://localhost:5000/images/testboosters/hunter-test.webp",
    },
    {
        id: 55,
        name: "Nugenix Total-T",
        category: "Testosterone Booster",
        description: "Boosts free and total testosterone levels.",
        brand: "Nugenix",
        image: "http://localhost:5000/images/testboosters/nugenix-total-t.jpg",
    },
    {
        id: 56,
        name: "Animal Test",
        category: "Testosterone Booster",
        description: "Enhances muscle-building and recovery.",
        brand: "Universal Nutrition",
        image: "http://localhost:5000/images/testboosters/animal-test.jpg",
    },
    {
        id: 57,
        name: "Alpha Test",
        category: "Testosterone Booster",
        description: "Scientifically designed for boosting strength and testosterone.",
        brand: "MuscleTech",
        image: "http://localhost:5000/images/testboosters/alpha-test.jpg",
    },
    {
        id: 58,
        name: "Test Stack No. 17",
        category: "Testosterone Booster",
        description: "Natural test booster for energy and endurance.",
        brand: "Test Stack",
        image: "http://localhost:5000/images/testboosters/test-stack-17.jpeg",
    },
    {
        id: 59,
        name: "Tribulus Terrestris Extract",
        category: "Testosterone Booster",
        description: "Supports testosterone levels and muscle growth.",
        brand: "NOW Sports",
        image: "http://localhost:5000/images/testboosters/tribulus-terrestris.jpeg",
    },
    {
        id: 60,
        name: "Iso-XP Protein",
        category: "Protein Supplement",
        description: "Ultra-pure whey isolate protein, high in protein and low in fat.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/protein/iso-xp.jpeg",
      },
      {
        id: 61,
        name: "Critical Whey",
        category: "Protein Supplement",
        description: "Advanced whey protein blend for muscle building and recovery.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/protein/critical-whey.webp",
      },
    
      
      {
        id: 62,
        name: "Amino Fuel",
        category: "Performance Supplement",
        description: "Essential amino acids blend to support recovery and muscle endurance.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/performance/amino-fuel.jpg",
      },
      {
        id: 63,
        name: "Pre-Workout Pump 3G",
        category: "Performance Supplement",
        description: "High-intensity pre-workout formula for enhanced energy and focus.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/performance/pump-3g.avif",
      },
    
      
      {
        id: 64,
        name: "Multivitamin Complex",
        category: "Vitamin Supplement",
        description: "Comprehensive multivitamin for overall health and immunity.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/vitamin/multivitamin-complex.jpg",
      },
      {
        id: 65,
        name: "Vitamin D3 + K2",
        category: "Vitamin Supplement",
        description: "Supports bone and cardiovascular health with essential vitamins.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/vitamin/vitamin-d3-k2.webp",
      },
    
     
      {
        id: 66,
        name: "CLA, L-Carnitine & Green Tea",
        category: "Weight Loss Supplement",
        description: "Blend of fat-burning ingredients to support weight management.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/weightloss/cla-l-carnitine.jpg",
      },
    
      {
        id: 68,
        name: "Critical Mass Professional",
        category: "Mass Gainer",
        description: "High-calorie mass gainer for muscle size and strength.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/massgainer/critical-mass-pro.jpeg",
      },
      {
        id: 69,
        name: "Critical Mass Original",
        category: "Mass Gainer",
        description: "Classic mass gainer with balanced protein and carbohydrate blend.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/massgainer/critical-mass-original.jpeg",
      },
    
     
      {
        id: 70,
        name: "Test X",
        category: "Testosterone Booster",
        description: "Natural testosterone booster for strength and recovery.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/testboosters/test-x.jpeg",
      },
      {
        id: 71,
        name: "Alpha Genesis",
        category: "Testosterone Booster",
        description: "Enhances natural testosterone production for energy and vitality.",
        brand: "Applied Nutrition",
        image: "http://localhost:5000/images/testboosters/alpha-genesis.jpg",
      },
];


module.exports = supplements;
